2026-09-05T14:23:35+02:00 deploying orbit 9eee6d15 + plugins c8c0c8de -> /home/chat/irc/webchat-new 2026-09-05T14:23:35+02:00 build orbit 2026-09-05T14:23:47+02:00 ERROR npm run build failed
> orbit@2.0.0-dev build
> tsc -b && vite build

src/components/chat/MemberList.tsx(48,28): error TS6133: 'onNavigate' is declared but its value is never read.